// Objective-C API for talking to goutils/goutils Go package.
//   gobind -lang=objc goutils/goutils
//
// File is generated by gobind. Do not edit.

#ifndef __Goutils_H__
#define __Goutils_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* GoutilsRsaDecrypt(NSString* pinToken, NSString* sessionId, NSString* secret, NSError** error);

FOUNDATION_EXPORT NSString* GoutilsUuidFromBytes(NSData* input, NSError** error);

#endif
