// Objective-C API for talking to tip/crypto Go package.
//   gobind -lang=objc tip/crypto
//
// File is generated by gobind. Do not edit.

#ifndef __Crypto_H__
#define __Crypto_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CryptoPoint;
@class CryptoScalar;
@class CryptoSuite;
@class CryptoSuiteBn256;

@interface CryptoPoint : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSData* _Nullable)publicKeyBytes;
- (NSString* _Nonnull)publicKeyString;
- (BOOL)verify:(NSData* _Nullable)msg sig:(NSData* _Nullable)sig error:(NSError* _Nullable* _Nullable)error;
@end

@interface CryptoScalar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSData* _Nullable)privateKeyBytes;
- (CryptoPoint* _Nullable)publicKey;
- (void)setBytes:(NSData* _Nullable)b;
- (NSData* _Nullable)sign:(NSData* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
@end

@interface CryptoSuite : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)initG2;
- (CryptoScalar* _Nullable)scalar;
@end

@interface CryptoSuiteBn256 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (CryptoScalar* _Nullable)scalar;
@end

FOUNDATION_EXPORT NSData* _Nullable CryptoDecrypt(CryptoPoint* _Nullable pub, CryptoScalar* _Nullable priv, NSData* _Nullable b);

FOUNDATION_EXPORT NSData* _Nullable CryptoEcdh(CryptoPoint* _Nullable point, CryptoScalar* _Nullable scalar);

FOUNDATION_EXPORT NSData* _Nullable CryptoEncrypt(CryptoPoint* _Nullable pub, CryptoScalar* _Nullable priv, NSData* _Nullable b);

FOUNDATION_EXPORT CryptoSuiteBn256* _Nullable CryptoNewSuiteBn256(void);

FOUNDATION_EXPORT CryptoSuite* _Nullable CryptoNewSuiteG2(void);

FOUNDATION_EXPORT CryptoScalar* _Nullable CryptoPrivateKeyFromHex(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT CryptoPoint* _Nullable CryptoPubKeyFromBase58(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT CryptoPoint* _Nullable CryptoPubKeyFromBytes(NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable CryptoRecoverSignature(NSString* _Nullable partialStrings, NSString* _Nullable commitmentStrings, NSData* _Nullable assignor, long signersLen, NSError* _Nullable* _Nullable error);

#endif
