
// Objective-C API for talking to the following Go packages
//
//	mixin/tip
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tip_FRAMEWORK_H__
#define __Tip_FRAMEWORK_H__

#include "Tip.objc.h"
#include "Universe.objc.h"

#endif
