// Objective-C API for talking to mixin/tip Go package.
//   gobind -lang=objc mixin/tip
//
// File is generated by gobind. Do not edit.

#ifndef __Tip_H__
#define __Tip_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSData* _Nullable TipDecrypt(NSString* _Nullable pb, NSString* _Nullable private, NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipEncrypt(NSString* _Nullable pb, NSString* _Nullable private, NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipNewPrivateKeyFromBytes(NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull TipPointPublicKeyString(NSData* _Nullable b);

FOUNDATION_EXPORT BOOL TipPointVerify(NSString* _Nullable pt, NSData* _Nullable msg, NSData* _Nullable sig, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipPublicKeyFromBytes(NSData* _Nullable rawScalar, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipRecoverSignature(NSString* _Nullable partialStrings, NSString* _Nullable commitmentStrings, NSData* _Nullable assignor, long signersLen, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipSignFromBytes(NSData* _Nullable rawScalar, NSData* _Nullable msg, NSError* _Nullable* _Nullable error);

#endif
