// Objective-C API for talking to github.com/crossle/goutils Go package.
//   gobind -lang=objc github.com/crossle/goutils
//
// File is generated by gobind. Do not edit.

#ifndef __Goutils_H__
#define __Goutils_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull GoutilsRsaDecrypt(NSString* _Nullable pinToken, NSString* _Nullable sessionId, NSString* _Nullable secret, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GoutilsUuidFromBytes(NSData* _Nullable input, NSError* _Nullable* _Nullable error);

#endif
