
// Objective-C API for talking to the following Go packages
//
//	github.com/crossle/goutils
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Goutils_FRAMEWORK_H__
#define __Goutils_FRAMEWORK_H__

#include "Goutils.objc.h"
#include "Universe.objc.h"

#endif
