
// Objective-C API for talking to the following Go packages
//
//	mixin/tip
//	mixin/kernel
//	mixin/ed25519
//	mixin/blockchain
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TIP_FRAMEWORK_H__
#define __TIP_FRAMEWORK_H__

#include "Tip.objc.h"
#include "Kernel.objc.h"
#include "Ed25519.objc.h"
#include "Blockchain.objc.h"
#include "Universe.objc.h"

#endif
