// Objective-C API for talking to mixin/blockchain Go package.
//   gobind -lang=objc mixin/blockchain
//
// File is generated by gobind. Do not edit.

#ifndef __Blockchain_H__
#define __Blockchain_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull BlockchainGenerateEthereumAddress(NSString* _Nullable seed, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull BlockchainGenerateSolanaAddress(NSString* _Nullable seed, NSError* _Nullable* _Nullable error);

#endif
