// Objective-C API for talking to mixin/tip Go package.
//   gobind -lang=objc mixin/tip
//
// File is generated by gobind. Do not edit.

#ifndef __Tip_H__
#define __Tip_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class TipPoint;
@class TipScalar;
@class TipSuite;
@class TipSuiteBn256;

@interface TipPoint : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSData* _Nullable)publicKeyBytes:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)publicKeyString:(NSError* _Nullable* _Nullable)error;
- (BOOL)verify:(NSData* _Nullable)msg sig:(NSData* _Nullable)sig error:(NSError* _Nullable* _Nullable)error;
@end

@interface TipScalar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (TipScalar* _Nullable)clone;
- (NSData* _Nullable)privateKeyBytes:(NSError* _Nullable* _Nullable)error;
- (TipPoint* _Nullable)publicKey;
- (void)setBytes:(NSData* _Nullable)b;
- (NSData* _Nullable)sign:(NSData* _Nullable)msg error:(NSError* _Nullable* _Nullable)error;
@end

@interface TipSuite : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)initG2;
- (TipScalar* _Nullable)scalar;
@end

@interface TipSuiteBn256 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
- (TipScalar* _Nullable)scalar;
@end

FOUNDATION_EXPORT NSData* _Nullable TipDecrypt(TipPoint* _Nullable pub, TipScalar* _Nullable priv, NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipEcdh(TipPoint* _Nullable point, TipScalar* _Nullable scalar, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipEncrypt(TipPoint* _Nullable pub, TipScalar* _Nullable priv, NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT TipSuiteBn256* _Nullable TipNewSuiteBn256(void);

FOUNDATION_EXPORT TipSuite* _Nullable TipNewSuiteG2(void);

FOUNDATION_EXPORT TipScalar* _Nullable TipPrivateKeyFromHex(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT TipPoint* _Nullable TipPubKeyFromBase58(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT TipPoint* _Nullable TipPubKeyFromBytes(NSData* _Nullable b, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable TipRecoverSignature(NSString* _Nullable partialStrings, NSString* _Nullable commitmentStrings, NSData* _Nullable assignor, long signersLen, NSError* _Nullable* _Nullable error);

#endif
